use Mix.Config

# Configure your database
config :event_app_spa, EventAppSpa.Repo,
  username: "event_app_spa",
  password: "VCvp2QUBEV8SCjN3",
  database: "event_app_spa_prod",
  hostname: "localhost",
  show_sensitive_data_on_connection_error: true,
  pool_size: 10

# For production, don't forget to configure the url host
# to something meaningful, Phoenix uses this information
# when generating URLs.
#
# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix phx.digest` task,
# which you should run after static files are built and
# before starting your production server.
config :event_app_spa, EventAppSpaWeb.Endpoint,
  url: [host: "events-spa.seablue.site", port: 80],
  cache_static_manifest: "priv/static/cache_manifest.json"

# Do not print debug messages in production
config :logger, level: :info

# Finally import the config/prod.secret.exs which loads secrets
# and configuration from environment variables.
import_config "prod.secret.exs"
